'use client'

import { useEffect, useMemo, useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import { Textarea } from '@/components/ui/textarea'
import { Camera, Check, ChevronRight, ClipboardList, Clock3, Eye, FileText, HelpCircle, LayoutDashboard, MapPin, Menu, Mic, Pause, Play, Plus, Search, Settings, Square, Users, WifiOff } from 'lucide-react'

const forms = [
  { code: 'ETN', title: 'Ficha de escena etnográfica', description: 'Describe lo que ocurre, quién participa y qué te llama la atención.', count: '12 campos', order: 1, state: 'Empieza aquí' },
  { code: 'OBS', title: 'Registro del espacio', description: 'Documenta materialidades, cambios, huellas y adaptaciones del territorio.', count: '9 campos', order: 2, state: 'Después' },
  { code: 'ENT', title: 'Guía de entrevista', description: 'Sigue preguntas por actor, repregunta y registra notas sin perder el hilo.', count: 'Guía dinámica', order: 3, state: 'Cuando converses' },
  { code: 'REC', title: 'Recorrido comentado', description: 'Camina, registra paradas con GPS y guarda el trayecto en un archivo CSV.', count: 'GPS + cámara', order: 4, state: 'En movimiento' },
  { code: 'MEM', title: 'Muro cronológico', description: 'Ordena hitos, agrega contexto y voltea cada post-it para profundizar.', count: 'Línea temporal', order: 5, state: 'Para cerrar' },
]

const recent = [
  { code: 'ETN-014', title: 'Escena etnográfica', author: 'María González', date: 'Hoy, 10:42', status: 'Sincronizado' },
  { code: 'OBS-008', title: 'Registro del espacio', author: 'Carlos Ruiz', date: 'Ayer, 16:15', status: 'Sincronizado' },
  { code: 'REC-021', title: 'Recorrido comentado', author: 'Ana Torres', date: 'Ayer, 13:08', status: 'Solo lectura' },
]

export function FieldDashboard() {
  const [activeView, setActiveView] = useState('Inicio')
  const [showForm, setShowForm] = useState(false)
  const [selectedForm, setSelectedForm] = useState(forms[0])
  const [saved, setSaved] = useState(false)
  if (showForm) return <CollectionForm form={selectedForm} onBack={() => setShowForm(false)} saved={saved} onSave={() => setSaved(true)} />
  return <div className="min-h-screen bg-muted/30 text-foreground">
    <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-18 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted lg:hidden" aria-label="Abrir menú"><Menu /></button><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ClipboardList /></div><div><p className="text-lg font-bold tracking-tight">Ayni Campo</p><p className="text-xs text-muted-foreground">Recolección cualitativa</p></div></div><div className="flex items-center gap-3"><Badge variant="outline" className="hidden gap-1.5 px-3 py-1.5 text-xs font-medium sm:flex"><WifiOff data-icon="inline-start" /> Trabajo sin conexión</Badge><div className="flex size-10 items-center justify-center rounded-full bg-secondary text-sm font-semibold">MG</div></div></div></header>
    <div className="mx-auto flex max-w-[1500px]"><aside className="hidden w-64 shrink-0 border-r bg-background lg:block"><nav className="flex flex-col gap-1 p-4" aria-label="Navegación principal">{[['Inicio', LayoutDashboard], ['Mis formularios', FileText], ['Registros del equipo', Users], ['Configuración', Settings]].map(([label, Icon]) => <button key={label as string} onClick={() => setActiveView(label as string)} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-left text-sm font-medium ${activeView === label ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-5" />{label as string}</button>)}</nav><Separator /><div className="p-5"><div className="flex items-start gap-3 rounded-xl bg-secondary/60 p-4"><HelpCircle className="mt-0.5 size-5 shrink-0 text-primary" /><div><p className="text-sm font-semibold">¿Necesitas ayuda?</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Consulta la guía de campo o contacta al coordinador.</p></div></div></div></aside>
      <main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-primary">Proyecto activo · Ayna — Agosto 2026</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Buenos días, María</h1><p className="mt-2 text-base text-muted-foreground">Elige la etapa de trabajo que corresponde a tu visita.</p></div><Button size="lg" className="h-12 gap-2 px-5" onClick={() => { setSelectedForm(forms[0]); setShowForm(true) }}><Plus data-icon="inline-start" />Nueva recolección</Button></div>
        <div className="mb-10 grid gap-4 sm:grid-cols-3"><Stat icon={ClipboardList} label="Mis registros" value="24" note="3 esta semana" /><Stat icon={Users} label="Equipo" value="8" note="6 activos hoy" /><Stat icon={Clock3} label="Pendientes" value="3" note="Listos para sincronizar" /></div>
        <section className="mb-10"><Card className="overflow-hidden border-border/70 shadow-sm"><CardHeader className="border-b bg-secondary/40"><div className="flex items-center justify-between gap-4"><div><CardTitle className="text-xl">Ruta de recolección</CardTitle><CardDescription className="mt-1">Las etapas muestran relación, no restringen el orden. Solo verás secciones si el administrador las configura.</CardDescription></div><Badge variant="outline">5 etapas</Badge></div></CardHeader><CardContent className="p-4 sm:p-6"><div className="grid gap-3 md:grid-cols-5">{forms.map((form, index) => <div key={form.code} className="relative flex gap-3 md:block"><div className={`flex size-10 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index === 0 ? 'bg-primary text-primary-foreground' : 'bg-primary/15 text-primary'}`}>{form.order}</div><div className="pt-1 md:pt-3"><p className="text-sm font-semibold">{form.title}</p><p className="mt-1 text-xs text-muted-foreground">{form.state}</p></div>{index < forms.length - 1 && <div className="absolute left-5 top-10 h-5 w-px bg-primary/30 md:left-[calc(100%+0.75rem)] md:top-5 md:h-px md:w-6" />}</div>)}</div></CardContent></Card></section>
        <section><div className="mb-5"><h2 className="text-xl font-bold">Instrumentos de recolección</h2><p className="mt-1 text-sm text-muted-foreground">Elige el instrumento según el momento del trabajo. Estas agrupaciones solo organizan la navegación; el administrador puede configurarlas.</p></div><div className="flex flex-col gap-6">{([{ title: 'Pre campo', description: 'Preparar la visita, revisar objetivos y dejar lista la guía.', codes: ['ENT', 'MEM'] }, { title: 'Campo', description: 'Registrar lo que ocurre en el lugar, durante la interacción o el recorrido.', codes: ['ETN', 'OBS', 'REC'] }, { title: 'Poscampo', description: 'Completar la reflexión y ordenar los hallazgos después de la visita.', codes: [] }] as const).map((group) => <div key={group.title} className="rounded-2xl border border-border/70 bg-background/60 p-4 sm:p-5"><div className="mb-4 flex items-start gap-3"><div className="mt-1 size-2.5 shrink-0 rounded-full bg-primary" /><div><h3 className="font-semibold">{group.title}</h3><p className="mt-1 text-sm text-muted-foreground">{group.description}</p></div></div>{group.codes.length === 0 ? <p className="rounded-xl border border-dashed bg-muted/30 p-4 text-sm text-muted-foreground">No hay instrumentos asignados a esta sección.</p> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{forms.filter((form) => group.codes.includes(form.code as typeof group.codes[number])).map((form) => <Card key={form.code} className="border-border/70 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><CardHeader><div className="mb-2 flex items-center justify-between"><div className="flex size-11 items-center justify-center rounded-xl bg-primary text-sm font-bold text-primary-foreground">{form.code}</div><Badge variant="secondary">{form.count}</Badge></div><CardTitle className="text-lg leading-snug">{form.title}</CardTitle><CardDescription className="min-h-10 leading-5">{form.description}</CardDescription></CardHeader><CardContent><Button variant={form.order === 1 ? 'default' : 'outline'} className="w-full" onClick={() => { setSelectedForm(form); setSaved(false); setShowForm(true) }}>{form.order === 1 ? 'Comenzar aquí' : 'Abrir instrumento'} <ChevronRight data-icon="inline-end" /></Button></CardContent></Card>)}</div>}</div>)}</div></section>
        <section className="mt-10"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">Registros recientes</h2><p className="mt-1 text-sm text-muted-foreground">Consulta los formularios enviados por todo el equipo.</p></div><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="h-9 w-56 pl-9" placeholder="Buscar registro" aria-label="Buscar registro" /></div></div><Card className="overflow-hidden border-border/70 shadow-sm"><div className="divide-y">{recent.map((item) => <div key={item.code} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="flex items-center gap-4"><div className="flex size-10 items-center justify-center rounded-lg bg-secondary"><FileText className="size-5 text-muted-foreground" /></div><div><p className="font-semibold">{item.title} <span className="ml-2 font-mono text-xs font-normal text-muted-foreground">{item.code}</span></p><p className="mt-1 text-sm text-muted-foreground">{item.author} · {item.date}</p></div></div><div className="flex items-center gap-3 pl-14 sm:pl-0"><Badge variant={item.status === 'Sincronizado' ? 'default' : 'secondary'} className="gap-1.5"><Check className="size-3.5" />{item.status}</Badge><Button variant="ghost" size="sm"><Eye data-icon="inline-start" />Ver</Button></div></div>)}</div></Card></section>
      </div></main></div></div>
}

function Stat({ icon: Icon, label, value, note }: { icon: typeof ClipboardList; label: string; value: string; note: string }) { return <Card className="border-border/70 shadow-sm"><CardContent className="flex items-center gap-4 p-5"><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></div><div><p className="text-sm text-muted-foreground">{label}</p><div className="flex items-baseline gap-2"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{note}</p></div></div></CardContent></Card> }

function NoteCard({ title, prompt, placeholder, required = false }: { title: string; prompt?: string; placeholder: string; required?: boolean }) { return <div className="rounded-2xl border border-primary/10 bg-secondary/45 p-4"><Label className="font-semibold">{title} {required && <span className="text-destructive">*</span>}</Label>{prompt && <p className="mt-1 text-sm italic text-muted-foreground">{prompt}</p>}<Textarea required={required} placeholder={placeholder} className="mt-3 min-h-28 resize-y border-0 bg-background/70 shadow-none focus-visible:ring-1" /></div> }

function StageSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-background p-4 shadow-sm sm:p-6"><div className="mb-5 border-b pb-4"><p className="text-xs font-semibold uppercase tracking-widest text-primary">{title}</p><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{children}</section> }

function CollectionForm({ form, onBack, saved, onSave }: { form: typeof forms[number]; onBack: () => void; saved: boolean; onSave: () => void }) {
  const [now, setNow] = useState({ date: '', time: '' }); const [location, setLocation] = useState('Detectando ubicación…'); const [recording, setRecording] = useState(false); const [followUps, setFollowUps] = useState<string[]>([]); const [stops, setStops] = useState(0)
  useEffect(() => { const date = new Date(); setNow({ date: date.toISOString().slice(0, 10), time: date.toTimeString().slice(0, 5) }); if ('geolocation' in navigator) navigator.geolocation.getCurrentPosition((p) => setLocation(`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`), () => setLocation('Ubicación no disponible')) }, [])
  const isInterview = form.code === 'ENT'; const isRoute = form.code === 'REC'; const isTimeline = form.code === 'MEM'
  const questions = ['Trayectoria y llegada al rol', 'Decisiones y prioridades', 'Relaciones visibles y cambios'];
  return <div className="min-h-screen bg-muted/30"><header className="sticky top-0 z-30 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-18 max-w-5xl items-center justify-between px-4 sm:px-6"><Button variant="ghost" onClick={onBack}>← Volver</Button><div className="text-center"><p className="font-semibold">{form.title}</p><p className="text-xs text-muted-foreground">Guardado automático activado</p></div><Badge variant="outline">{form.code}-015</Badge></div></header>{isInterview && <div className="sticky top-[73px] z-20 border-b bg-primary px-4 py-2 text-primary-foreground"><div className="mx-auto flex max-w-5xl items-center justify-between"><span className="text-sm font-medium">Grabación de la sesión</span><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setRecording(!recording)}>{recording ? <Pause data-icon="inline-start" /> : <Play data-icon="inline-start" />}{recording ? 'Pausar' : 'Iniciar grabación'}</Button><Button size="sm" variant="ghost" className="text-primary-foreground" onClick={() => setRecording(false)}><Square data-icon="inline-start" />Detener</Button></div></div></div>}
    <main className="mx-auto max-w-5xl p-4 sm:p-8"><div className="mb-8"><p className="mb-2 text-sm font-medium text-primary">{form.code}-015 · Etapa {form.order} de 5</p><h1 className="text-3xl font-bold tracking-tight">{form.title}</h1><p className="mt-2 text-muted-foreground">{isRoute ? 'Registra el recorrido sin apartar la vista del camino.' : 'Sigue las secciones configuradas por el administrador. Los datos automáticos siempre quedan al final.'}</p></div>
      <div className="mb-6 grid gap-2 sm:grid-cols-3">{['Pre campo', 'Campo', 'Poscampo'].map((stage, index) => <div key={stage} className={`rounded-lg border px-3 py-2 text-sm ${index === 1 ? 'border-primary bg-primary/10 font-semibold' : 'bg-background text-muted-foreground'}`}><span className="mr-2 font-mono">0{index + 1}</span>{stage}</div>)}</div>
      <div className="flex flex-col gap-5"><StageSection title="Pre campo" description="Preparación y configuración antes de iniciar la recolección.">{isInterview ? <><Label htmlFor="actor">Perfil de actor</Label><select id="actor" className="mt-2 h-12 w-full rounded-lg border bg-background px-3"><option>Alcalde</option><option>Directivos</option><option>Enfermería</option><option>Familias</option></select><div className="mt-5 rounded-xl border bg-secondary/30 p-4"><p className="font-semibold">Índice de preguntas</p><nav className="mt-3 flex flex-col gap-2" aria-label="Índice de preguntas">{questions.map((question, index) => <a key={question} href={`#pregunta-${index + 1}`} className="text-sm text-primary hover:underline">{index === 0 ? '★ ' : ''}{index + 1}. {question}</a>)}</nav></div></> : <p className="text-sm text-muted-foreground">Revisa el objetivo de la etapa y prepara los materiales necesarios.</p>}</StageSection>
      <StageSection title="Campo" description="Registra la experiencia mientras ocurre, sin interrumpir el flujo.">{isRoute && <Card className="mb-5 overflow-hidden"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Tracker espacial manos libres</CardTitle><CardDescription>Trayecto guardado como puntos GPS para exportar a CSV.</CardDescription></div><Badge variant="secondary"><Clock3 data-icon="inline-start" /> 00:18:42</Badge></CardHeader><CardContent><div className="flex h-44 items-center justify-center rounded-xl bg-secondary/60 text-muted-foreground"><MapPin className="mr-2 text-primary" /> Mini-mapa offline · {location}</div><Button size="lg" className="mt-4 w-full gap-2" onClick={() => setStops(stops + 1)}><MapPin data-icon="inline-start" />Registrar parada{stops ? ` (${stops})` : ''}</Button></CardContent></Card>}{isTimeline && <Card className="mb-5"><CardHeader><CardTitle>Muro cronológico digital</CardTitle><CardDescription>Agrega hitos y ordénalos en la línea temporal.</CardDescription></CardHeader><CardContent><div className="flex min-h-36 items-center justify-center rounded-xl bg-secondary/45"><div className="h-px w-full bg-primary/40" /></div><Button variant="outline" className="mt-4 gap-2"><Plus data-icon="inline-start" />Nuevo post-it</Button></CardContent></Card>}{!isTimeline && !isRoute && <><div id="pregunta-1"><NoteCard title={isInterview ? '1. Trayectoria y llegada al rol' : '¿Qué te llamó la atención?'} prompt={isInterview ? '¿Cómo se enteró y qué fue lo primero que decidió? (¿Cómo así? ¿Por qué?)' : undefined} placeholder={isInterview ? 'Anota palabras clave, frases textuales o ideas para repreguntar sin detener el flujo.' : 'Detalles como dónde estabas, quiénes estaban presentes o cómo interactuaban.'} required={!isInterview} /></div>{isInterview && <>{followUps.map((_, index) => <div key={index} id={`repregunta-${index + 1}`}><NoteCard title={`Repregunta ${index + 1}`} prompt="¿Qué más puedes contarme sobre esto? (¿Por qué? ¿Qué ocurrió después?)" placeholder="Anota la respuesta y su trazabilidad." /></div>)}<Button variant="outline" className="w-fit gap-2" onClick={() => setFollowUps([...followUps, `repregunta-${followUps.length + 1}`])}><Plus data-icon="inline-start" />Añadir repregunta</Button></>}{isRoute && <NoteCard title="Explicación de los actores" placeholder="Describe quiénes estaban y qué hacían." />}</>}</StageSection>
      <StageSection title="Poscampo" description="Cierra la sesión con tu lectura y el contexto que ayudará al análisis.">{isInterview && <div className="flex flex-col gap-5"><NoteCard title="Reflexión del entrevistador" placeholder="Tu reflexión o sensación inmediata al terminar la reunión (máximo 2 a 3 líneas)." /><NoteCard title="Contexto de la sesión" placeholder="Interrupciones, clima general, tiempo real utilizado y preguntas núcleo no realizadas." /><NoteCard title="Turnos de habla y silencios" placeholder="¿Quién abrió la conversación, quién completaba frases o quién calló o se incomodó?" /></div>}{!isInterview && <NoteCard title="Notas de cierre" placeholder="Resume hallazgos, pendientes o incidencias de esta etapa." />}</StageSection></div>
      <Card className="mt-6"><CardHeader><CardTitle>Datos automáticos</CardTitle><CardDescription>Se completan por defecto y se colocan siempre al final.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-3"><div><Label htmlFor="date">Fecha</Label><Input id="date" type="date" value={now.date} readOnly className="mt-2 h-12" /></div><div><Label htmlFor="time">Hora</Label><Input id="time" type="time" value={now.time} readOnly className="mt-2 h-12" /></div><div><Label>GPS</Label><div className="mt-2 flex h-12 items-center gap-2 rounded-lg border bg-secondary/40 px-3 text-sm"><MapPin className="size-4 text-primary" />{location}</div></div></CardContent></Card>
      <div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={onSave}>Guardar borrador</Button><Button onClick={onSave}>Enviar registro <ChevronRight data-icon="inline-end" /></Button></div>{saved && <p className="mt-4 text-right text-sm font-medium text-primary">Registro guardado correctamente.</p>}</main></div>
}

export function AdminHint() { return <div className="sr-only">Los administradores pueden crear, editar y eliminar proyectos, formularios, preguntas, usuarios y registros.</div> }
